server.port=3002
spring.application.name=blog-service

# MongoDB
spring.data.mongodb.host=${MONGO_HOST:mongodb}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.database=${MONGO_DATABASE:blog_db}
spring.data.mongodb.username=${MONGO_USER:}
spring.data.mongodb.password=${MONGO_PASSWORD:}

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

# Logging
logging.level.root=INFO
logging.level.com.das.blogservice=DEBUG
